# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9ed995e97ba697c78f6a531aa21c3a2af0790a11893fa7ffaa3422eb30e585ff7de57c3cedf629453e3c41b9f62e41e2a5208de82b7e4f535c1b823806bbdfdb

test:
  secret_key_base: 14db0ca4d70190081240610a6d38859ec48f74ac8cbd0f70d588c9341d2b9f6e7f3644d2945d1f2b89eada4d8d9e741aa251cd2249ca533ab06d56c641d32f0b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
